name: Test and Deploy

env: # Change these settings when you need to
  ARTIFACT_NAME: individueel-project-1.3
  DOTNET_CORE_VERSION: 8.0.x
  PUBLISH_DIRECTORY: "./out/publish"
on:
  push:
    branches:
      - master
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  #test:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: game-ci/unity-test-runner@v4
        #with:
          #githubToken: ${{ secrets.PAT }}

  deploy-api:
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Itskillerluc/individueel-project-1.3-api/actions/workflows/145549007/dispatches \
          -d '{"ref":"master"}'
