name: Test and Deploy

env: # Change these settings when you need to
  ARTIFACT_NAME: individueel-project-1.3
  DOTNET_CORE_VERSION: 8.0.x
  PUBLISH_DIRECTORY: "./out/publish"
on:
  push:
    branches:
      - master
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  #build:
    #runs-on: ubuntu-latest
    #steps:

      #- uses: actions/checkout@v4
      #- name: Setup .NET
        #uses: actions/setup-dotnet@v4
        #with:
          #dotnet-version: ${{env.DOTNET_CORE_VERSION}}

      #- name: Restore dependencies
        #run: dotnet restore

      #- name: Build
        #run: dotnet build --no-restore

      #- name: Test
        #run: dotnet test --no-build --verbosity normal

  deploy-api:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="Itskillerluc" 
          repo_name="individueel-project-1.3-api"  
          event_type="trigger-workflow" 
          service="${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"

          curl -L \ -X POST \ -H "Accept: application/vnd.github+json" \ -H "Authorization: Bearer ${{ secrets.PAT }}" \ -H "X-GitHub-Api-Version: 2022-11-28" \ https://api.github.com/repos/$repo_owner/$repo_name/dispatches \ -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
