name: Test and Deploy

on:
  push:
    branches:
      - master
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  testing:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}       

  deploy-api:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Itskillerluc/individueel-project-1.3-api/actions/workflows/145549007/dispatches \
          -d '{"ref":"master"}'
