name: Test and Deploy

env: # Change these settings when you need to
  ARTIFACT_NAME: individueel-project-1.3
  DOTNET_CORE_VERSION: 8.0.x
  PUBLISH_DIRECTORY: "./out/publish"
on:
  push:
    branches:
      - master
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_CORE_VERSION}}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  deploy-api:
    uses: Itskillerluc/individueel-project-1.3-api/github/workflows/deployment.yml@master
    needs: build